avator_1:
 preparation: True # your can set it to False if you want to use the existing avator, it will save time
 bbox_shift: 5
 video_path: "data/video/yongen.mp4"
 audio_clips:
     audio_0: "temp/avatars/2e054776-92ea-4fb6-8f92-55d9eb3f7726/input_audio.m4a"

 
  

